Need ruby-dev in order to install fog gem
Without ruby-dev on Ubuntu 14.04, running gem install fog causes the following error:

 gem install fog

Building native extensions.    This could take a while...

ERROR:    Error installing fog:

	 ERROR: Failed to build gem native extension.



         /usr/bin/ruby1.9.1 extconf.rb

/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)

	 from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'

	 from extconf.rb:4:in `<main>'